[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["cd backend && python -m pip install --upgrade pip && python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "cd backend && python main.py"