services:
  - type: web
    name: quiz-app-backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install --upgrade pip
      pip install fastapi==0.104.1 uvicorn==0.24.0 python-multipart==0.0.6 pydantic==2.5.0
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT