services:
  - type: web
    name: quiz-app-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r backend/requirements.txt
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDir: .
    
  - type: web
    name: quiz-app-frontend
    env: static
    buildCommand: echo "No build needed for static site"
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html